version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0.30
    command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}:-password"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: "${MYSQL_USER}:-user"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}:-password"
      MYSQL_DATABASE: "${MYSQL_DATABASE}:-dbname"
    env_file:
      - .env
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - ./init.sql:/data/application/init.sql
