version: '3.8'

services:
  db:
    container_name: db
    image: mariadb
    #  command: --init-file /data/application/init.sql
    ports:
      - "3306:3306"
        #environment:
      #  MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}:-password"
      #  MARIADB_ROOT_PASSWORD: "password"
      #  MYSQL_ALLOW_EMPTY_PASSWORD: 1
      #  MARIADB_USER: "${MYSQL_USER}:-user"
      #  MARIADB_USER: "user"
      #  MARIADB_PASSWORD: "${MYSQL_PASSWORD}:-password"
      #  MARIADB_DATABASE: "dbname"
      #  MARIADB_PASSWORD: "${MYSQL_PASSWORD}:-password"
      #  MARIADB_DATABASE: "dbname"
    env_file:
      - .env
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./init.d:/docker-entrypoint-initdb.d/:ro"
      - ./dbdata:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
